environment:
    vmsHome: C:/Data/VirtualMachines/VirtualBox
master:
    machine: master
    name: CO7U8_CLD_MSTR
    hostname: "master.makker.local"
    #vmMemory: 12288 # 12*1024 MB 
    #vmMemory: 8192 # 8*1024 MB
    #vmMemory: 6144 # 6*1024 MB
    vmMemory: 4096 # 4*1024 MB
    vmCpus: 1
    vmGui: false
    #vmGui: true
    vmMonitorCount: 1
    #vmMonitorCount: 2    
    ssh:
        username: "vagrant"
        password: "vagrant"
    disks:
        controller: SATA
        disk2:
            name: disk2
            size: 524288 #1024 * 512
    sharedFolders:
        stage:
            hostFolder: c:/Data/git/makker/vagrant/Stage
            guestFolder: /media/sf_Stage
        project:
            hostFolder: c:/Data/git/makker
            guestFolder: /media/sf_Projects