# -*- mode: ruby -*-
# vi: set ft=ruby :
#
BOX_NAME="OL8.2SwGUIv1.0"
BOX_URL="file://../boxes/OL8.2SwGUIv1.0.box"
#VM_MEMORY = 12288 # 12*1024 MB
#VM_MEMORY = 8192 # 8*1024 MB
VM_MEMORY = 6144 # 6*1024 MB
#VM_MEMORY = 6656 # 6,5*1024 MB
VM_CPUS=2
VM_GUI=false
#VM_GUI=true
#VMS_HOME="d:\\VirtualMachines\\VirtualBox"
VMS_HOME="C:/Data/VirtualMachines/VirtualBox"
VM_NAME="OL8U2_RH_FUSE"  
VM_HOST_NAME="rhfuse.conclusion.local"
VM_MACHINE="rhfuse"
VM_STORAGE_CTRL="SATA"  
VM_DISK2=VMS_HOME+"/"+VM_NAME+"/"+VM_NAME+".disk2.vdi"
VM_DISK2_SIZE=1024 * 512
# Stage folders
STAGE_HOST_FOLDER="d:/Projects/vagrant/Stage"
STAGE_GUEST_FOLDER="/media/sf_Stage"
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box=BOX_NAME
  config.vm.box_url=BOX_URL
  config.vm.hostname=VM_HOST_NAME
  config.vm.define VM_MACHINE
  config.vm.provider :virtualbox do |vb|
    vb.name=VM_NAME
    vb.gui=VM_GUI
    vb.memory=VM_MEMORY
    vb.cpus=VM_CPUS
	#Pre-allocate the memory when starting the guest.
	#vb.customize ["setextradata", :id, "VBoxInternal/RamPreAlloc", 1]
    # Set clipboard and drag&drop bidirectional
    vb.customize ["modifyvm", :id, "--clipboard-mode", "bidirectional"]
    vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
    # Create a disk  
    unless File.exist?(VM_DISK2)
      vb.customize [ "createmedium", "disk", "--filename", VM_DISK2, "--format", "vdi", "--size", VM_DISK2_SIZE , "--variant", "Standard" ]
    end
    # Add it to the VM.
    vb.customize [ "storageattach", :id , "--storagectl", VM_STORAGE_CTRL, "--port", "2", "--device", "0", "--type", "hdd", "--medium", VM_DISK2]
  end
  config.ssh.username="vagrant"
  config.ssh.password="vagrant"
  #Base Mac address.
  #config.vm.base_mac="080027126D17"
  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder STAGE_HOST_FOLDER, STAGE_GUEST_FOLDER
  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  $initScript = <<-SCRIPT
    export SCRIPT_HOME=/media/sf_Stage/commonScripts/linux
    echo _______________________________________________________________________________
    echo Prepare Oracle Linux
    $SCRIPT_HOME/OL8Prep.sh
    echo _______________________________________________________________________________
    echo 1. Create Filesystem
    $SCRIPT_HOME/OL8FileSystem.sh
    echo _______________________________________________________________________________
    echo 2. Create RedHat User
    $SCRIPT_HOME/OL8MakeRedHatUser.sh
  SCRIPT
  #
  # Install Java 8 script
  $installJava8Script = <<-SCRIPT
    export SCRIPT_HOME=/media/sf_Stage/commonScripts/fmw/java/jdk8
    echo _______________________________________________________________________________
    echo Java SDK 8
    CMD=${SCRIPT_HOME}/installJava8.sh
    sudo runuser -l redhat -c $CMD
  SCRIPT
  #
  # Install Maven script
  $installMavenScript = <<-SCRIPT
    export SCRIPT_HOME=/media/sf_Stage/commonScripts/opensource/maven
    echo _______________________________________________________________________________
    echo Maven
    CMD=${SCRIPT_HOME}/installMaven.sh
    sudo runuser -l redhat -c $CMD
  SCRIPT
  #
  # Install Eclipse script
  $installEclipseScript = <<-SCRIPT
    export SCRIPT_HOME=/media/sf_Stage/commonScripts/opensource/Eclipse
    echo _______________________________________________________________________________
    echo Eclipse
    CMD=${SCRIPT_HOME}/installEclipse.sh
    sudo runuser -l redhat -c $CMD
  SCRIPT
  #
  # Install RedHat CodeReadyStudio script
  $installCodeReadyStudioScript = <<-SCRIPT
    export SCRIPT_HOME=/media/sf_Stage/commonScripts/redhat/CodeReadyStudio
    echo _______________________________________________________________________________
    echo RedHat CodeReadyStudio
    CMD=${SCRIPT_HOME}/installCodeReadyStudio.sh
    sudo runuser -l redhat -c $CMD
  SCRIPT
  #
  # Install Camel script
  $installCamelScript = <<-SCRIPT
    export SCRIPT_HOME=/media/sf_Stage/commonScripts/opensource/Camel
    echo _______________________________________________________________________________
    echo Camel
    CMD=${SCRIPT_HOME}/installCamel.sh
    sudo runuser -l redhat -c $CMD
  SCRIPT
  #
config.vm.provision "init", type: "shell", run: "once", inline: $initScript
config.vm.provision "installJava8", type: "shell", run: "once", inline: $installJava8Script
config.vm.provision "installMaven", type: "shell", run: "once", inline: $installMavenScript
config.vm.provision "installEclipse", type: "shell", run: "once", inline: $installEclipseScript
config.vm.provision "installCodeReadyStudio", type: "shell", run: "once", inline: $installCodeReadyStudioScript
config.vm.provision "installCamel", type: "shell", run: "once", inline: $installCamelScript
end