#!/bin/bash
SCRIPTPATH=$(dirname $0)
OS_HOME=/app/opensource
ECLIPSE_VERSION=2023-03
ECLIPSE_INSTALL_NAME=Eclipse-${ECLIPSE_VERSION}
ECLIPSE_HOME=$OS_HOME/$ECLIPSE_INSTALL_NAME/eclipse
echo start Eclipse ${ECLIPSE_VERSION}
$ECLIPSE_HOME/eclipse > $SCRIPTPATH/eclipse.out 2>&1 & 
